# Loosely based on the cadvisor Dockerfile, without support for ipmctl
#   https://github.com/google/cadvisor/blob/master/deploy/Dockerfile
package:
  name: cadvisor
  version: 0.47.0 # libpfm version may also need updating - check cadvisor Dockerfile
  epoch: 0
  description: "Analyzes resource usage and performance characteristics of running containers"
  target-architecture:
    - x86_64
  copyright:
    - paths:
      - "*"
      attestation: 'Copyright 2014 The cAdvisor Authors'
      license: 'Apache License 2.0'
  dependencies:
    runtime:
      - device-mapper
      - findutils
      - ndctl
      - thin-provisioning-tools

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - cmake
      - device-mapper
      - findutils
      - git
      - linux-headers
      - ndctl-dev
      - thin-provisioning-tools

pipeline:
  # Fetch and build libpfm
  - uses: fetch
    with:
      uri: https://sourceforge.net/projects/perfmon2/files/libpfm4/libpfm-4.11.0.tar.gz
      expected-sha256: 5da5f8872bde14b3634c9688d980f68bda28b510268723cc12973eedbab9fecc
      strip-components: 0
  - runs: |
      pwd
      ls -al
      export DBG="-g -Wall"
      make -e -C libpfm-4.11.0
      make install -C libpfm-4.11.0

  # Fetch cadvisor binary release
  - uses: fetch
    with:
      uri: https://github.com/google/cadvisor/releases/download/v${{package.version}}/cadvisor-v${{package.version}}-linux-amd64
      expected-sha256: caf4491298e0702f9d0c6a1d1949767f5c6400f77e12cd3524d6d3fcc66abc2a
      extract: false

  # Package libpfm and cadvisor
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin/
      mkdir -p ${{targets.destdir}}/usr/local/lib/
      chmod +x cadvisor-v${{package.version}}-linux-amd64
      cp cadvisor-v${{package.version}}-linux-amd64 ${{targets.destdir}}/usr/bin/cadvisor
      cp /usr/local/lib/libpfm.so* ${{targets.destdir}}/usr/local/lib/

